apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "buildah-unprivileged.fullname" . }}
  labels:
    {{- include "buildah-unprivileged.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "buildah-unprivileged.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "buildah-unprivileged.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "buildah-unprivileged.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: registry.redhat.io/rhel8/buildah@sha256:0a86ecbdfbe86e9d225b7fe4b090a0dd6d323f8afdfdf2bd933ff223ddb53320
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          command: 
            - "/bin/bash"
          args: 
            - "-c"
            - "buildah --storage-driver=vfs bud --format=oci --tls-verify=false --no-cache -f /etc/configmaps/dockerfile -t test ."
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - name: varlibcontainers
              mountPath: /home/build/.local/share/containers
            - name: dockerfile
              mountPath: /etc/configmaps
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}          
      volumes:
      - name: varlibcontainers
        emptyDir: {}
      - name: dockerfile
        configMap:
          name: dockerfile
