---
kind: SecurityContextConstraints
metadata:
  annotations:
  name: buildah-scc-userid-1000 
allowHostDirVolumePlugin: false
allowHostIPC: false
allowHostNetwork: false
allowHostPID: false
allowHostPorts: false
allowPrivilegeEscalation: false
allowPrivilegedContainer: false
allowedCapabilities: null
apiVersion: security.openshift.io/v1
defaultAddCapabilities: null
fsGroup:
  type: MustRunAs
groups:
- system:cluster-admins
priority: 10
readOnlyRootFilesystem: false
requiredDropCapabilities:
- MKNOD
runAsUser: 
  type: MustRunAs
  uid: 1000
seLinuxContext:
  type: MustRunAs
supplementalGroups:
  type: RunAsAny
users: []
volumes:
- configMap
- downwardAPI
- emptyDir
- persistentVolumeClaim
- projected
- secret
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: buildah-scc-userid-1000-clusterrole 
rules:
- apiGroups:
  - security.openshift.io
  resourceNames:
  {{- if .Values.privileged  }}
  - privileged
  {{- else }}
  - buildah-scc-userid-1000
  {{- end }}
  resources:
  - securitycontextconstraints
  verbs:
  - use
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: buildah-scc-userid-1000-rolebinding 
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: buildah-scc-userid-1000-clusterrole
subjects:
- kind: ServiceAccount
  name: {{ include "buildah-unprivileged.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
